# Generated by Django 4.1.1 on 2022-09-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_subcategory_product_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_title',)},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('category_title',)},
        ),
    ]
