# Generated by Django 4.1.1 on 2022-10-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketline',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
