# Generated by Django 4.1.1 on 2022-10-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_basketline_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
